Add Theme for Warp Terminal
mtyn/polar pull request #14
Opened 2024-03-07 00:47 UTC by obahareth

This is my attempt to implement #13.

I am not sure if I am supposed to do something on the generator side or if this file is enough.

I am not sure if I got the accent color right or not, from their docs it says:
"Accent color for UI elements"

2024-03-07 09:05 UTC, mtyn requested changes

2024-03-07 09:05 UTC, mtyn commented on polar/warp/polar.yaml
> +accent: "#ff2600"
This needs to be one of the Polar colors - otherwise you get the red line shown here as the UI highlight. I'd suggest `#81a1c1` probably to line up with other themes.

<img width="291" alt="Screenshot 2024-03-07 at 09 04 22" src="https://github.com/mtyn/polar/assets/9058064/3949802d-cbb0-43bd-94cc-2d7ceea86ffd">

2024-03-07 09:06 UTC, mtyn commented
No need to do anything with the generator - I'll be removing that very soon

2024-03-07 13:00 UTC, obahareth commented on polar/warp/polar.yaml
> +accent: "#ff2600"
Done!

2024-03-10 09:45 UTC, mtyn approved these changes
Thanks for this PR - let's get it merged!

2024-03-10 09:45 UTC, merged